#!/usr/bin/env python3
"""Exhaustive edge-level proof for the color-neutral first Megaminx phase.

Input files phase1_antipodes_block_0.bin ... _19.bin are generated by
all_phase1_antipodes_range.cpp.  Each contains the 159 depth-10 states for
one choice of the solved 2x2x2 block (one corner plus its three edges).

The verifier deliberately RELAXES the full-puzzle consistency problem:
corner placements and all corner orientation constraints are ignored.  It
keeps only
  * agreement for every edge shared by its two endpoint blocks; and
  * the requirement that the 30 edge pieces occupy 30 distinct positions.
If even this relaxation has no even edge permutation, then no legal
Megaminx state can put every first-block choice at depth 10, since each face
turn is a 5-cycle on edges and therefore preserves even edge parity.
"""
from __future__ import annotations

import struct
from collections import defaultdict, deque
from pathlib import Path

BLOCKS = 20
EDGES = 30
ANTIPODES = 159
ROOT = Path(__file__).resolve().parent


def read_domains():
    domains = []
    incidences = []
    for block in range(BLOCKS):
        path = ROOT / "antipodes" / f"phase1_antipodes_block_{block}.bin"
        data = path.read_bytes()
        count = struct.unpack_from("<I", data, 0)[0]
        incident = tuple(data[4:7])
        assert count == ANTIPODES, (path, count)
        assert len(data) == 7 + 6 * count, (path, len(data))

        # Collapse states that differ only in the ignored corner coordinate.
        signatures = set()
        for i in range(count):
            cp, co, p0, p1, p2, eo = struct.unpack_from("6B", data, 7 + 6 * i)
            del cp, co
            signatures.add(
                (
                    (incident[0], (p0, (eo >> 2) & 1)),
                    (incident[1], (p1, (eo >> 1) & 1)),
                    (incident[2], (p2, eo & 1)),
                )
            )
        # dict: target edge piece -> (position, orientation)
        domains.append([dict(sig) for sig in sorted(signatures)])
        incidences.append(incident)
    return domains, incidences


DOMAINS, INCIDENCES = read_domains()
assert all(len(d) == 80 for d in DOMAINS), [len(d) for d in DOMAINS]

EDGE_BLOCKS = defaultdict(list)
for block, incident in enumerate(INCIDENCES):
    for edge in incident:
        EDGE_BLOCKS[edge].append(block)
assert set(EDGE_BLOCKS) == set(range(EDGES))
assert all(len(v) == 2 for v in EDGE_BLOCKS.values())

NEIGHBORS = [dict() for _ in range(BLOCKS)]
for edge, (u, v) in EDGE_BLOCKS.items():
    NEIGHBORS[u][v] = edge
    NEIGHBORS[v][u] = edge
assert all(len(n) == 3 for n in NEIGHBORS)

# Compatibility masks for the single edge shared by adjacent blocks.
COMPAT = [[None] * BLOCKS for _ in range(BLOCKS)]
for edge, (u, v) in EDGE_BLOCKS.items():
    for a, b in ((u, v), (v, u)):
        buckets = defaultdict(int)
        for j, option in enumerate(DOMAINS[b]):
            buckets[option[edge]] |= 1 << j
        COMPAT[a][b] = [buckets[option[edge]] for option in DOMAINS[a]]

INITIAL = [(1 << len(DOMAINS[b])) - 1 for b in range(BLOCKS)]


def revise(masks, u, v):
    old = masks[u]
    new = 0
    x = old
    while x:
        bit = x & -x
        i = bit.bit_length() - 1
        x -= bit
        if COMPAT[u][v][i] & masks[v]:
            new |= bit
    masks[u] = new
    return new != old


def ac3(masks, queue=None):
    q = deque(
        queue
        if queue is not None
        else ((u, v) for u in range(BLOCKS) for v in NEIGHBORS[u])
    )
    while q:
        u, v = q.popleft()
        if revise(masks, u, v):
            if masks[u] == 0:
                return False
            for w in NEIGHBORS[u]:
                if w != v:
                    q.append((w, u))
    return True


def supported_values(masks, edge):
    """All supported (position, orientation) values of one target edge."""
    u, v = EDGE_BLOCKS[edge]
    values = set()
    x = masks[u]
    while x:
        bit = x & -x
        i = bit.bit_length() - 1
        x -= bit
        if COMPAT[u][v][i] & masks[v]:
            values.add(DOMAINS[u][i][edge])
    return values


def propagate(masks):
    """Arc consistency + global all-different edge positions."""
    if not ac3(masks):
        return None

    while True:
        values = [supported_values(masks, edge) for edge in range(EDGES)]
        if any(not x for x in values):
            return None

        # Singleton target-edge assignments reserve their positions.
        owner = {}
        for edge, vals in enumerate(values):
            if len(vals) == 1:
                position, orientation = next(iter(vals))
                del orientation
                previous = owner.get(position)
                if previous is not None and previous != edge:
                    return None
                owner[position] = edge

        changed_blocks = []
        for block in range(BLOCKS):
            old = masks[block]
            new = 0
            x = old
            while x:
                bit = x & -x
                i = bit.bit_length() - 1
                x -= bit
                option = DOMAINS[block][i]
                valid = True
                for edge, (position, orientation) in option.items():
                    del orientation
                    occupied_by = owner.get(position)
                    if occupied_by is not None and occupied_by != edge:
                        valid = False
                        break
                if valid:
                    new |= bit
            if new == 0:
                return None
            if new != old:
                masks[block] = new
                changed_blocks.append(block)

        if not changed_blocks:
            return values

        queue = []
        for block in changed_blocks:
            for neighbor in NEIGHBORS[block]:
                queue.append((neighbor, block))
        if not ac3(masks, queue):
            return None


def permutation_parity(permutation):
    return sum(
        permutation[i] > permutation[j]
        for i in range(len(permutation))
        for j in range(i + 1, len(permutation))
    ) & 1


def cycle_lengths(permutation):
    seen = set()
    lengths = []
    for start in range(len(permutation)):
        if start in seen:
            continue
        x = start
        length = 0
        while x not in seen:
            seen.add(x)
            length += 1
            x = permutation[x]
        if length > 1:
            lengths.append(length)
    return sorted(lengths)


CONFIGURATIONS = set()
NODES = 0


def search(masks):
    global NODES
    NODES += 1
    masks = masks[:]
    values = propagate(masks)
    if values is None:
        return

    if all(len(vals) == 1 for vals in values):
        positions = tuple(next(iter(vals))[0] for vals in values)
        orientations = tuple(next(iter(vals))[1] for vals in values)
        assert sorted(positions) == list(range(EDGES))
        CONFIGURATIONS.add((positions, orientations))
        return

    # Branch on the most constrained non-singleton block domain.
    candidates = [b for b in range(BLOCKS) if masks[b].bit_count() > 1]
    block = min(candidates, key=lambda b: masks[b].bit_count())
    x = masks[block]
    while x:
        bit = x & -x
        x -= bit
        child = masks[:]
        child[block] = bit
        search(child)


search(INITIAL)

print("phase-1 antipodes per block:", ANTIPODES)
print("unique edge signatures per block:", len(DOMAINS[0]))
print("search nodes:", NODES)
print("global relaxed edge configurations:", len(CONFIGURATIONS))

parities = []
for number, (positions, orientations) in enumerate(sorted(CONFIGURATIONS)):
    parity = permutation_parity(positions)
    parities.append(parity)
    lengths = cycle_lengths(positions)
    print(f"configuration {number}: parity={'odd' if parity else 'even'}; "
          f"flipped_edges={sum(orientations)}; cycle_lengths={lengths}")
    assert lengths == [2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3]
    print("  edge_piece_to_position:", " ".join(map(str, positions)))

assert len(CONFIGURATIONS) == 5
assert parities == [1, 1, 1, 1, 1]
print("VERIFIED: every relaxed all-antipode configuration has odd edge parity.")
print("CONCLUSION: no legal Megaminx state has all 20 first-block distances equal to 10.")
